# Generated by Django 5.0.3 on 2024-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
