# Generated by Django 4.2.11 on 2024-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10)),
                ('kilometragem', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('is_reservado', models.BooleanField()),
                ('is_disponivel', models.BooleanField()),
                ('motorista', models.CharField(max_length=50)),
            ],
        ),
    ]
