# Generated by Django 5.0.3 on 2024-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('requerente', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
    ]
