# Generated by Django 5.0.3 on 2024-03-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('data_compra', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedor.fornecedor')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requisicao.requisicao')),
            ],
        ),
    ]
