# Generated by Django 5.0.3 on 2024-03-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
        ('item', '0003_alter_item_descricao'),
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='items',
            field=models.ManyToManyField(to='item.item'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requisicao.requisicao'),
        ),
    ]
