# Generated by Django 5.0.3 on 2024-03-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_items_alter_compra_requisicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='items',
            new_name='itens',
        ),
    ]
